[GNSS-SDR]
GNSS-SDR.internal_fs_sps=4000000

[SignalSource]
implementation=File_Signal_Source
filename=simulation_standard.bin
item_type=ishort
sampling_frequency=4000000
samples=0

[SignalConditioner]
implementation=Signal_Conditioner
sample_freq_in=4000000
sample_freq_out=4000000

[DataTypeAdapter]
implementation=Ishort_To_Complex

[Channel0]
implementation=Channel
[Channel1]
implementation=Channel
[Channel2]
implementation=Channel
[Channel3]
implementation=Channel
[Channel4]
implementation=Channel
[Channel5]
implementation=Channel
[Channel6]
implementation=Channel
[Channel7]
implementation=Channel

[Acquisition_1C]
implementation=GPS_L1_CA_PCPS_Acquisition
doppler_max=10000
doppler_step=250

[Tracking_1C]
implementation=GPS_L1_CA_DLL_PLL_Tracking
pll_bw_hz=40.0
dll_bw_hz=4.0

[Telemetry_1C]
implementation=GPS_L1_CA_Telemetry_Decoder

[Observables]
implementation=GPS_L1_CA_Observables

[PVT]
implementation=Rinex_Printer
rinex_version=3
output_filename=rover_simulated.obs
